// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/metric.proto

// protoc --go_out=. --go_opt=paths=source_relative   --go-grpc_out=. --go-grpc_opt=paths=source_relative   proto/metric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_Type int32

const (
	Metric_GAUGE   Metric_Type = 0
	Metric_GOUNTER Metric_Type = 1
)

// Enum value maps for Metric_Type.
var (
	Metric_Type_name = map[int32]string{
		0: "GAUGE",
		1: "GOUNTER",
	}
	Metric_Type_value = map[string]int32{
		"GAUGE":   0,
		"GOUNTER": 1,
	}
)

func (x Metric_Type) Enum() *Metric_Type {
	p := new(Metric_Type)
	*p = x
	return p
}

func (x Metric_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metric_proto_enumTypes[0].Descriptor()
}

func (Metric_Type) Type() protoreflect.EnumType {
	return &file_proto_metric_proto_enumTypes[0]
}

func (x Metric_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_Type.Descriptor instead.
func (Metric_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{0, 0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Metric_Type            `protobuf:"varint,2,opt,name=type,proto3,enum=metric.Metric_Type" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() Metric_Type {
	if x != nil {
		return x.Type
	}
	return Metric_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_proto_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_proto_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_proto_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_proto_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EncryptedMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedData string                 `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMetrics) Reset() {
	*x = EncryptedMetrics{}
	mi := &file_proto_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMetrics) ProtoMessage() {}

func (x *EncryptedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMetrics.ProtoReflect.Descriptor instead.
func (*EncryptedMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptedMetrics) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

type UpdateEncrypteMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEncrypteMetricsRequest) Reset() {
	*x = UpdateEncrypteMetricsRequest{}
	mi := &file_proto_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEncrypteMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEncrypteMetricsRequest) ProtoMessage() {}

func (x *UpdateEncrypteMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEncrypteMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateEncrypteMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEncrypteMetricsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateEncrypteMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEncrypteMetricsResponse) Reset() {
	*x = UpdateEncrypteMetricsResponse{}
	mi := &file_proto_metric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEncrypteMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEncrypteMetricsResponse) ProtoMessage() {}

func (x *UpdateEncrypteMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEncrypteMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateEncrypteMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEncrypteMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_metric_proto protoreflect.FileDescriptor

const file_proto_metric_proto_rawDesc = "" +
	"\n" +
	"\x12proto/metric.proto\x12\x06metric\"\x8d\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.metric.Metric.TypeR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"\x1e\n" +
	"\x04Type\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aGOUNTER\x10\x01\"=\n" +
	"\x13UpdateMetricRequest\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.metric.MetricR\x06metric\",\n" +
	"\x14UpdateMetricResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"@\n" +
	"\x14UpdateMetricsRequest\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.metric.MetricR\ametrics\"-\n" +
	"\x15UpdateMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\x10EncryptedMetrics\x12%\n" +
	"\x0eencrypted_data\x18\x01 \x01(\tR\rencryptedData\"2\n" +
	"\x1cUpdateEncrypteMetricsRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"5\n" +
	"\x1dUpdateEncrypteMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x88\x02\n" +
	"\aMetrics\x12I\n" +
	"\fUpdateMetric\x12\x1b.metric.UpdateMetricRequest\x1a\x1c.metric.UpdateMetricResponse\x12L\n" +
	"\rUpdateMetrics\x12\x1c.metric.UpdateMetricsRequest\x1a\x1d.metric.UpdateMetricsResponse\x12d\n" +
	"\x15UpdateEncrypteMetrics\x12$.metric.UpdateEncrypteMetricsRequest\x1a%.metric.UpdateEncrypteMetricsResponseB\x0eZ\fmetric/protob\x06proto3"

var (
	file_proto_metric_proto_rawDescOnce sync.Once
	file_proto_metric_proto_rawDescData []byte
)

func file_proto_metric_proto_rawDescGZIP() []byte {
	file_proto_metric_proto_rawDescOnce.Do(func() {
		file_proto_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)))
	})
	return file_proto_metric_proto_rawDescData
}

var file_proto_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_metric_proto_goTypes = []any{
	(Metric_Type)(0),                      // 0: metric.Metric.Type
	(*Metric)(nil),                        // 1: metric.Metric
	(*UpdateMetricRequest)(nil),           // 2: metric.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),          // 3: metric.UpdateMetricResponse
	(*UpdateMetricsRequest)(nil),          // 4: metric.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil),         // 5: metric.UpdateMetricsResponse
	(*EncryptedMetrics)(nil),              // 6: metric.EncryptedMetrics
	(*UpdateEncrypteMetricsRequest)(nil),  // 7: metric.UpdateEncrypteMetricsRequest
	(*UpdateEncrypteMetricsResponse)(nil), // 8: metric.UpdateEncrypteMetricsResponse
}
var file_proto_metric_proto_depIdxs = []int32{
	0, // 0: metric.Metric.type:type_name -> metric.Metric.Type
	1, // 1: metric.UpdateMetricRequest.metric:type_name -> metric.Metric
	1, // 2: metric.UpdateMetricsRequest.metrics:type_name -> metric.Metric
	2, // 3: metric.Metrics.UpdateMetric:input_type -> metric.UpdateMetricRequest
	4, // 4: metric.Metrics.UpdateMetrics:input_type -> metric.UpdateMetricsRequest
	7, // 5: metric.Metrics.UpdateEncrypteMetrics:input_type -> metric.UpdateEncrypteMetricsRequest
	3, // 6: metric.Metrics.UpdateMetric:output_type -> metric.UpdateMetricResponse
	5, // 7: metric.Metrics.UpdateMetrics:output_type -> metric.UpdateMetricsResponse
	8, // 8: metric.Metrics.UpdateEncrypteMetrics:output_type -> metric.UpdateEncrypteMetricsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_metric_proto_init() }
func file_proto_metric_proto_init() {
	if File_proto_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metric_proto_goTypes,
		DependencyIndexes: file_proto_metric_proto_depIdxs,
		EnumInfos:         file_proto_metric_proto_enumTypes,
		MessageInfos:      file_proto_metric_proto_msgTypes,
	}.Build()
	File_proto_metric_proto = out.File
	file_proto_metric_proto_goTypes = nil
	file_proto_metric_proto_depIdxs = nil
}
